name: Build and deploy Node.js app to Azure Web App - CampusSafetyApp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, run jest testing and start the app (for cypress)
        run: |
          npm install
          cd ./client
          npm install --force
          cd ..
          npm test
          npm start &

      - name: Cypress run
        run: |
          cd ./client
          npx cypress run

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: LukeRenton/CampusSafetyApp
          verbose: true


      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'  # Only run on push events
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CE638CFB1114B3FBE3C7849C8213100 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5150E07E329248BC8E7E5F1F37CF4BC4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C5FC85CD3E25411786F9AAC87272C5F9 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CampusSafetyApp'
          slot-name: 'Production'
          package: .
